services:
  plc-server:
    container_name: "plc-server"
    hostname: "plc-server"
    image: node-server:latest
    pull_policy: build
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 4840 || exit 1"]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: on-failure:5
    build:
      context: ${REF}opcua/server/nodejs-node-opcua/latest
      args:
        NODESET_MODEL: "PLC.NodeSet2.xml"
      additional_contexts:
        container_context: ${REF}opcua/server/nodejs-node-opcua/latest
        nodeset_context: ${META}/demo-nodeset2
        companion_context: ${META}/companion-specifications
        configuration_context: ${META}/server-configuration
    ports:
      - "4842:4840"
    networks:
      - plc-net
  plc-historian:
    container_name: "plc-historian"
    hostname: "plc-historian"
    image: historian:latest
    pull_policy: build
    restart: on-failure:5
    environment:
      - SERVER_URI=opc.tcp://plc-server:4840/KRITIS3M/
    volumes:
      - /tmp/docker/database:/database
    build:
      context: ${REF}opcua/historian/python-opcua-asyncio/latest
      additional_contexts:
        container_context: ${REF}opcua/historian/python-opcua-asyncio/latest
    networks:
      - plc-net
    depends_on:
      - plc-server
  plc-logic:
    container_name: "plc-logic"
    hostname: "plc-logic"
    image: plc-logic:latest
    pull_policy: build
    restart: on-failure:5
    environment:
      - PS_URI=opc.tcp://plc-server:4840
      - LSS_URI=opc.tcp://${WATER_SENSOR_SERVER_IP}:4840
      - VS_URI=opc.tcp://${VALVE_SERVER_IP}:4841
    build:
      context: ${REF}opcua/plc-logic/python-opcua-asyncio/latest
      additional_contexts:
        container_context: ${REF}opcua/historian/python-opcua-asyncio/latest
    networks:
      - plc-net
    depends_on:
      - plc-server
networks:
  plc-net:
    name: plc-net
    external: false